#!/bin/sh

self="${0##*git-}"
option="--$self"

# LONG_USAGE exported by git-sh-setup.
# shellcheck disable=2034
# git-sh-setup dynamically expands variables in LONG_USAGE.
# shellcheck disable=2016
LONG_USAGE='$self the ongoing rebase, am, revert, or cherry-pick action'

# See git-sh-setup(1)
# shellcheck disable=1090
. "$(git --exec-path)/git-sh-setup"

cd_to_toplevel

# A couple more revert and cherry-pick edge cases in __git_sequencer_status.
# Ignore them until somebody complains.
if   test -d .git/rebase-merge     ; then action=rebase
elif test -d .git/rebase-apply     ; then
    if test -f .git/rebase-apply/applying ; then
        action=am
    else
        action=rebase
    fi
elif test -f .git/MERGE_HEAD       ; then action=merge
elif test -f .git/REVERT_HEAD      ; then action=revert
elif test -f .git/CHERRY_PICK_HEAD ; then action=cherry-pick
fi

# $dashless comes from git-sh-setup.
# shellcheck disable=2154
test -n "$action" || die "$dashless: don't know how to '$option' current state"

if test "$action" = merge -a "$option" = --skip ; then
    die "$dashless: cannot '--skip' a merge"
fi

exec git "$action" "$option"
